[Match]
Profiles=desktop
Distribution=ubuntu

[Content]
# RemovePackages=
#     packagekit
#     totem
#     snapshot
Packages=
    ubuntu-desktop-minimal
    gnome-initial-setup
    dconf-gsettings-backend
    gsettings-desktop-schemas
    python3-nautilus
    ptyxis