[Match]
Profiles=desktop
Distribution=ubuntu

[Content]
# RemovePackages=
#     packagekit
#     totem
#     snapshot
Packages=
    ubuntu-desktop-minimal
    yaru-theme-gtk
    yaru-theme-gnome-shell
    yaru-theme-icon
    yaru-theme-sound
    fonts-recommended
    fonts-ubuntu
    fonts-ubuntu-console
    dconf-gsettings-backend
    gsettings-desktop-schemas
    python3-nautilus
    ptyxis