name: Build Ubuntu (base) DDI

permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
  pull_request:
    branches:
      - master
      - sysupdate
  schedule:
    - cron: "0 1 * * TUE"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-ddi.yaml
    secrets: inherit
    with:
      image-name: ubuntu
      platforms: amd64,arm64
      publish: ${{ github.event_name != 'pull_request' }}
